### ISSUE TITLE
Support for pocsag

### ISSUE THREAD

**Issue by tomswinkels** [dmitryelj/RPi-P2000Receiver#10]
Maybe its a good idea to add support for pocsag?

**Comment by dmitryelj** [comment]
I tested, it works, yes.
I've commited beta support for POCSAG messages. The proper frequency should be also set.

**Comment by tomswinkels** [comment]
Thnx, it works :)

**Comment by tomswinkels** [comment]
Afther some time the application is already running but there are comes no new messages. When i stop and restart them the messages are comming back from some time.

![image](https://user-images.githubusercontent.com/9036151/54613933-dce53900-4a5b-11e9-8ad4-d2e17c7cdd7a.png)

**Comment by dmitryelj** [comment]
Can you copy and send the full log from this console window?

**Comment by tomswinkels** [comment]
How can i do that?

**Comment by dmitryelj** [comment]
You can also scroll up the console window and check if there are any error
message there.

**Comment by tomswinkels** [comment]
I don't see any error. I use the post function.

**Comment by tomswinkels** [comment]
Here a new screen:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9036151/54630968-4f194600-4a7b-11e9-8f5d-3e373d3b780a.png">

There i see some error:

dataThreadFunc::Error in line:  <class 'UnicodeDecodeError'> p2000.py 590 'utf-8' codec can't decode byte 0xff in position 254: invalid start byte

**Comment by dmitryelj** [comment]
Thanks for screenshot. Fixed now.
