### ISSUE TITLE
cb transfer status: 1, canceling...

### ISSUE THREAD

**Issue by tomswinkels** [dmitryelj/RPi-P2000Receiver#11]
Sometimes i get the following message in the terminal and than i don't get new messages.

'cb transfer status: 1, canceling...'

![image](https://user-images.githubusercontent.com/9036151/55729072-b9d3f680-5a15-11e9-8300-5e75c3aeef03.png)

**Comment by dmitryelj** [comment]
According to this thread, its a power rtlsdr problem:
https://github.com/antirez/dump1090/issues/33

**Comment by tomswinkels** [comment]
Thnx!
