### ISSUE TITLE
Line contains ALN or NUM

### ISSUE THREAD

**Issue by M1K3-NL** [dmitryelj/RPi-P2000Receiver#20]
Hi, I have one more little question for you. Maybe you can help. It's the last "issue" I have, so I won't bother you after this haha.

Most of the FLEX messages is: 
`FLEX|2020-10-17 18:40:22|1600/2/K/A|10.021|001523161|ALN|A2 Zadelmaker ALPHRN Directe inzet 16161`
or
`FLEX: 2018-07-29 11:43:27 1600/2/K/A 10.120 [001523172] ALN A1 Boerhaavelaan HAARLM : 16172`

But now I have a capcode with a different sort of line:
`FLEX: 2020-10-17 18:40:19 1600/2/A 10.020 [001530615] NUM 3301`
Where 3301 is the message and NUM is the ALN. 

Now the script is filtering on ALN by doing: message = line[line.find("ALN")+4:].strip()
How can I add NUM to the line.find of the old FLEX code.
![ShareX_EAQOQhuj4p](https://user-images.githubusercontent.com/39988281/96351172-f75d1980-10b9-11eb-9403-c5921eac44c2.png)

**Comment by M1K3-NL** [comment]
For now I have this running, but I only can test it if the 3301 NUM coming in and that's 0-10 times a day.

![sublime_text_ZERGBDKeGZ](https://user-images.githubusercontent.com/39988281/96351380-2d4ecd80-10bb-11eb-9008-6d6bc3564ff6.png)

**Comment by dmitryelj** [comment]
First you can switch back to the last multimon-ng version, then you do not need _line[line.find("ALN")+4:]_ substring more. Only thing to add, will be `if line.__contains__("ALN") or line.__contains__("NUM")`, it should be enough. Or if you want, you can use something like `message = line[line.find("ALN")+4:].strip() if "ALN" in line else line[line.find("NUM")+4:].strip()` or any another check, you want. In general, switching to the last multimon-ng looks more easy.

I did not see this message before so cannot confirm that it works, but in theory it should be.

**Comment by M1K3-NL** [comment]
Hi, yes it's only in region 15 Haaglanden for some police code like narcotics, weapons and explosives service and the arrest team negotiator.

**Comment by M1K3-NL** [comment]
I'll look at your ideas tomorrow 🙂

**Comment by M1K3-NL** [comment]
Hello, both are working as you said. So you can add them to your own script if you like. 🙂

I'll close the issue now.

**Comment by dmitryelj** [comment]
Thanks. Added to the main project.
