### ISSUE TITLE
Feature: group messages

### ISSUE THREAD

**Issue by tomswinkels** [dmitryelj/RPi-P2000Receiver#3]
When a message has more than one capcode i want that in a group.

**Comment by dmitryelj** [comment]
Can you show a screenshot how it should look like?

**Comment by tomswinkels** [comment]
On this moment i use PDW, but i think this works better :-)

I wan't this;

```
09:36:13 20-06-18  GROUP-1  A1 AMBU 18197 De Manning 2995AE Heerjansdam HEERJD bon
1420999  
1423001  
1423397  
2029568  
```

The problem now is that you append the receivers to the messages, but i want only display the message in onetime with all the receivers.

**Comment by tomswinkels** [comment]
Any update?

**Comment by tomswinkels** [comment]
The problem now is that you append the receivers to the messages, but i want only display the message in onetime with all the receivers.

**Comment by tomswinkels** [comment]
I have create a pull for my idea; https://github.com/dmitryelj/RPi-P2000Receiver/pull/4

**Comment by dmitryelj** [comment]
You can do it in javascript, changing index.html buildHtmlTable method, where the table is creating. The message already contains a list of receivers, you need to change only the view.

**Comment by tomswinkels** [comment]
Javascript are not an option. I see that you have commit a post function that will help!
