### ISSUE TITLE
Bug, regex prio

### ISSUE THREAD

**Issue by tomswinkels** [dmitryelj/RPi-P2000Receiver#5]
This message "Prio 4 A12 R 36,5 BODEGR Loslopende dieren" are set to prio 1, but it is prio 4.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/9036151/44325029-cb04ce80-a457-11e8-8120-aeb0f250249e.png">

**Comment by tomswinkels** [comment]
This message `B1 5223GZ : Henri Dunantstraat 's-Hertogenbosch Obj: Ziekenhuis JBZ Hoofd JBZ A2 Zuid Rit: 99217` is matching on A2, not on B1.

**Comment by dmitryelj** [comment]
Updated, should be better now.
