### ISSUE TITLE
Post data other format

### ISSUE THREAD

**Issue by tomswinkels** [dmitryelj/RPi-P2000Receiver#6]
Hi,

The post data has some raw format "capcodes=002029568&capcodes=000120999&capcodes=000120117&type=message&timestamp=2019-02-04+22%3A14%3A48&body=A1+13117+Rit+14864+Landsmeer+Weegbreesingel+1121XZ"

But when i send it to an PHP script and will get the $_POST data than i get;

```
{
capcodes: "001523183",
type: "message",
body: "B1 LUMC (K2-R) SEH LUMC Ambulancehal Brugmansplein LEIDEN : 16183",
timestamp: "2019-02-04 22:18:39"
}
```

You see only one capcode and not an array, maybe you can fix this?

**Comment by tomswinkels** [comment]
I have make a pull https://github.com/dmitryelj/RPi-P2000Receiver/pull/7

**Comment by dmitryelj** [comment]
Merged, thanks.
